### ISSUE TITLE
Inconsistent formatting of the "Map setup" sectioin in co-op scenarios

### ISSUE THREAD

**Issue by Dima793** [qwrtln/Homm3BG-mission-book#145]
I've noticed that "Map setup" sectioin tile list formatting varies in different sources for different game mode scenarios. 

Official non-campaign scenarios use bullet points for each map tile type. 
*Example 1: Archon Studio's Mission Book, version 1.0 ENG, p. 9.* 
![изображение](https://github.com/user-attachments/assets/95b47860-47b4-440b-a737-75c89b29dda1) 
*Example 2: Archon Studio's Mission Book, version 1.0 ENG, p. 12.* 
![изображение](https://github.com/user-attachments/assets/7ec30ed9-e1a8-4293-b903-17bb8bfc3049) 

On the other hand, official campaign scenarios use bold text, with bullet points for particular tile factions and codes. 
*Example 3: Archon Studio's Mission Book, version 1.0 ENG, p. 20.* 
![изображение](https://github.com/user-attachments/assets/15a47892-c9d9-4db2-9c49-d9bb914ebbd5) 

But co-op scenarios in fan-made mission book use the latter approach to formatting for some reason. 
*Example 4: Fan-Made Mission Book, version built on GitHub from commit [af2bfbe](https://github.com/qwrtln/Homm3BG-mission-book), p. 13.* 
![изображение](https://github.com/user-attachments/assets/b02af77b-d54c-4eed-b29a-32e3fc770df9) 
While campaign and clash game mode scenarios formatting approaches in fan-made mission book do align with official scenarios' formatting.

I suggest using formatting approaches consistent with official scenarios, and therefore using bullet point formatting (Example 1/2) rather than bold text formatting (Example 3) for co-op scenarios in fan-made mission book.

**Comment by Dima793** [comment]
P.S. When creating new issues, your project only allows to choose between a bug report and a scenario submission. This issue doesn't technically fall into either category. Maybe add a free form for other issues?

**Comment by qwrtln** [comment]
Thanks for reporting. Actually for the existing coop scenarios it's not as simple, because instead of listing tiles for every case (say, 2-6 in case of Titans' Stronghold), there's a formula. How would you prefer this to be formatted exactly? For Sentinels this could work, but for the remaining two coop scenarios I don't see the formatting in Archon's docs working.

**Comment by Dima793** [comment]
> How would you prefer this to be formatted exactly? 

As I've said in my initial report, I suggest using non-campaign formatting from the oficial books, as shown in Examples 1 and 2. Actually, "All for one" scenario map setup section seems to be a good example of how Archon formats map tile lists with additional notes, presenting 5 kinds of notes: 
1. Tile content (Grail) note — no separator 
![изображение](https://github.com/user-attachments/assets/f66731b6-9a2f-4a6a-9b4c-9a3333a87889) 
2. Tile subset (3/6) content note — after a comma 
![изображение](https://github.com/user-attachments/assets/ef4ec01e-ab41-427e-b7f6-2867a6ac090e)
3. Player personal tiles note — after a dash 
![изображение](https://github.com/user-attachments/assets/10ba3c79-a2fe-4bfc-8dd1-c4ffa915b786)
4. Suggested tile placement positions note — in brackets 
![изображение](https://github.com/user-attachments/assets/10ba3c79-a2fe-4bfc-8dd1-c4ffa915b786)
5. Tile placement rules (rather than just exact positions) — a separate paragraph below the list 
![изображение](https://github.com/user-attachments/assets/db90dccf-242c-40f5-b850-1584f58a54c0)
I have to admit I'm a fan of universal formatting/wording. I believe it streamlines user experience, eases information digestion and reduces potential for misinterpretation. Nut it might be just my preference to have exactly the same wording repeating every time.

**Comment by qwrtln** [comment]
Can you make a pull request with this? That way, we could visualize the diff and see if the text still fits within the pages.

**Comment by Dima793** [comment]
> For Sentinels this could work, but for the remaining two coop scenarios I don't see the formatting in Archon's docs working.

I don't see what's the issue here tbh. Describing map setup for every player count separately might be cumbersome, so can use the "P" as a new wording template, that's a great solution. I see it as having more than 2 player counts being a use case that didn't occur in the official books, so it can have a new template solution. But it isn't in any way connected to the "bold text with bullet points" vs "just bullet points" formatting inconsistency that I've described above. I can describe how I'd format/word Titan's Stronghold scenario's "Map setup" section for example, so you'll see what I mean:

> MAP SETUP
> Take the following Map Tiles and arrange them as shown in the Scenario map layout (P stands for the number of players):
> - P × Starting (I) Map Tile
> - 2P × Far (II–III) Map Tile
> - 2P × Near (IV–V) Map Tile
> - (P + 1) × Center (VI–VII) Map Tile
> **NOTE:** If you don’t have enough Center Tiles, you can
use another Tile near Starting Tiles. The center of this
Tile is the Titans’ Stronghold.

There are two bullet point notes in the current fan mission book version of this scenario that I omitted above:
> Starting Tiles of your chosen Factions

I believe this note is redundant. It's not used in official scenarios while clearly implied.
> Ignore their yellow borders.

I believe this note should belong to "Additional rules" section instead, similar to how it's in the official books. 
*Example: Archon Studio's Stretch Goals Mission Book, version 1.0 ENG, p. 5.* 
![изображение](https://github.com/user-attachments/assets/fd1c34df-31ad-45b3-a6cf-a76c170844ad)

Emerald Island scenario is almost the same in terms of formatting. And Sentinels too - not sure why you say it might be ok for this scenario but not for the other two.

**Comment by Dima793** [comment]
> Can you make a pull request with this? That way, we could visualize the diff and see if the text still fits within the pages.

That requires more than just making a couple comments from mobile 😅

**Comment by qwrtln** [comment]
This is a communal best-effort project ¯\_(ツ)_/¯
This change has the highest chance of happening if you make it. You know best the desired outcome, and what you want to see.

**Comment by Dima793** [comment]
That's a fair point.
