### ISSUE TITLE
where do we leave feedback after playtesting the maps?

### ISSUE THREAD

**Issue by yotamolenik** [qwrtln/Homm3BG-mission-book#42]
I didn't see any dedicated place for that, nor any mention of it
maybe the place would be discord?

**Comment by qwrtln** [comment]
We're still figuring it out. In the meantime, you can create issues like these.

**Comment by qwrtln** [comment]
Join us here: https://discord.gg/962pNrne

**Comment by yotamolenik** [comment]
sorry for the big delay, but now the link doesn't work
